name: corvi
description: Ublue-OS based image with the Cosmic desktop environment.

base-image: ghcr.io/blue-build/base-images/fedora-cosmic
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user

  - type: signing
