name: corvi
description: Ublue-OS based image with the Cosmic desktop environment.

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    group-install:
      packages:
        - admin-tools
        - basie-graphical
        - core
        - cosmic-desktop
        - cosmic-desktop-apps
        - desktop-accessibility
        - dial-up
        - fonts
        - guest-desktop-agents
        - hardware-support
        - input-methods
        - multimedia
        - networkmanager-submodules
        - printing
        - standard

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user

  - type: signing
  - type: systemd
    system:
      enabled:
        - cosmic-greeter
